"""ajustador campos para monitorar as tarefas

Revision ID: 01d8f6836384
Revises: c84029761e68
Create Date: 2025-04-21 15:23:30.568992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d8f6836384'
down_revision = 'c84029761e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_executed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('executions_today', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('today_categories', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('today_categories')

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('executions_today')
        batch_op.drop_column('last_executed')

    # ### end Alembic commands ###
